idf_component_register(
                        SRC_DIRS .
                        INCLUDE_DIRS "include"
                        REQUIRES 
                            esp_timer 
                            freertos
                            device
                            device_gpio
                    )
                    


