idf_component_register(SRC_DIRS .
                        INCLUDE_DIRS .
                        REQUIRES cmock unity 
                        PRIV_REQUIRES 
                        device 
                        device_i2c 
                        driver 
                        event_manager
                    )
