idf_component_register(
                        SRC_DIRS .
                        INCLUDE_DIRS "include"
                        PRIV_REQUIRES
                            lwip
                            bgcp
                            wifi_service
                            device
                    )
                    


